# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: /apis/user-java/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/user-java
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 for Shared Runner
      uses: actions/setup-java@v1
      with:
        java-version: 11
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: alialaa/issue-action@v1.0.0
      if: failure()
      with:
        token: ${{github.token}}
        title: found issue with test ${{github.workflow}}!
        body: Workflow ${{github.run_number }} Failed!. Repo is ${{github.repository}}
        
       
