# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: /apis/user-java/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/user-java
      
    steps:
   
         
    - uses: actions/checkout@v2
    - name: Set up JDK 11 for Shared Runner
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package --file pom.xml 
    - uses: azure/docker-login@v1
      with:
         login-server: ${{secrets.ACR_USERNAME }} # default: index.docker.io
         username: ${{ secrets.ACR_PASSWORD }}
         password: ${{ secrets.ACR_LOGINSERVER }}
      
    - name: build docker image
      run: |
         docker build . -t openhacka8d3h114acr.azurecr.io/dtadevops-apis:${{github.run_number }}
         docker push openhacka8d3h114acr.azurecr.io/dtadevops-apis:${{github.run_number }}
    - uses: Azure/webapps-deploy@v2
      with:
       app-name: openhacka8d3h114userjava
       publish-profile:  ${{ secrets.azureWebAppPublishProfile }}
       slot-name: staging
       images: openhacka8d3h114acr.azurecr.io/dtadevops-apis:${{ github.run_number }}
    - uses: alialaa/issue-action@v1.0.0
      if: failure()
      with:
        token: ${{github.token}}
        title: found issue with test ${{github.workflow}}!
        body: Workflow ${{github.run_number }} Failed!. Repo is ${{github.repository}}
    

              
       
